name: GCP Workload Identity Federation

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Terraform
        run: |
          curl -LO "https://releases.hashicorp.com/terraform/1.3.0/terraform_1.3.0_linux_amd64.zip"
          unzip terraform_1.3.0_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform -v

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve