name: GCP Workload Identity Federation

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          export_default_credentials: true

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with: 
          terraform_version: 1.3.0  # Specify your desired version

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve